### PR TITLE
Barrierefreiheitserklärung

### LINKED ISSUE #104: Add Barrierefreiheitserklärung to footer
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Add Barrierefreiheitserklärung to footer

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

_No response_

### LINKED ISSUE #118: Social media links not opening in new window
### Current Behavior

Top right Social media links not opening in new window

### Reproduction / Steps To Reproduce

1. Go to site
2. Click on twitter logo
3. See error

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by maehr**
# Pull request

## Proposed changes

- Fix #104 
- Fix #118 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [x] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[README](./README.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **New Features**
	- Added a "Barrierefreiheit" (Accessibility) link in the navigation section for improved accessibility.

### CODE REVIEW

File: src/routes/+layout.svelte [hunk 1]
```diff
@@ -135,6 +135,8 @@
 					<span class="mx-2 opacity-10">|</span>
 					<a class="anchor" href="/datenschutzerklaerung">Datenschutz</a>
 					<span class="mx-2 opacity-10">|</span>
+					<a class="anchor" href="/barrierefreiheitserklaerung">Barrierefreiheit</a>
+					<span class="mx-2 opacity-10">|</span>
```
Comment (mtwente) [inline src/routes/+layout.svelte:139]:
```suggestion
					<span class="mx-2 opacity-10 aria-hidden="true">|</span>
					<a class="anchor" href="/datenschutzerklaerung">Datenschutz</a>
					<span class="mx-2 opacity-10 aria-hidden="true">|</span>
					<a class="anchor" href="/barrierefreiheitserklaerung">Barrierefreiheit</a>
					<span class="mx-2 opacity-10 aria-hidden="true">|</span>
```

**Review by mtwente — CHANGES_REQUESTED** [review]

**Review by mtwente — APPROVED** [review]
